# Generated by Django 6.0.4 on 2026-04-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_uuid', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('stream_url', models.URLField(max_length=1000)),
                ('homepage', models.URLField(blank=True, max_length=1000)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('language', models.CharField(blank=True, max_length=128)),
                ('tags', models.TextField(blank=True)),
                ('favicon', models.URLField(blank=True, max_length=1000)),
                ('bitrate', models.PositiveIntegerField(default=0)),
                ('clickcount', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-clickcount', 'name'],
            },
        ),
    ]
