# Generated by Django 6.0.4 on 2026-04-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='genre',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
