# Generated by Django 6.1 on 2026-09-01 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=512, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StationTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='radio.station')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_on', to='radio.track')),
            ],
            options={
                'ordering': ['-played_at'],
                'indexes': [models.Index(fields=['station', '-played_at'], name='idx_station_played_at')],
            },
        ),
    ]
